Repository boostcamp-2020/Project16-C-Account-Book, pull requests merged in 2020-12, with the labels that each got.

#65 Refactor sass
  FE/src/components/Calendar/calendar.scss
  FE/src/components/CategoryChart/PieChart/pieChart.scss
  FE/src/components/CategoryChart/TableChart/tableChart.scss
  FE/src/components/Chart/NavButton/navButton.scss
  FE/src/components/Common/MenuBar/index.tsx
  FE/src/components/Common/MenuBar/menubar.scss
  FE/src/components/PaymentMethod/AddTemplate/addForm.scss
  FE/src/components/PaymentMethod/AddTemplate/index.tsx
  FE/src/components/PaymentMethod/CardContainer/cardContainer.scss
  FE/src/components/PaymentMethod/CardContainer/index.tsx
  FE/src/components/PaymentMethod/Modal/index.tsx
  FE/src/components/PaymentMethod/Modal/modal.scss
  FE/src/components/PaymentMethod/NewMethod/index.tsx
  FE/src/components/PaymentMethod/NewMethod/newMethod.scss
  FE/src/pages/Calendar/calendar.scss
  FE/src/pages/Calendar/index.tsx
  FE/src/store/TransactionData/transactionData.ts
  FE/src/styles/defaultCards.scss
  FE/src/styles/mixins.scss
  FE/src/styles/values.scss
Labels: frontend, refactor

#63 [BE] DB Model 작업
  .vscode/settings.json
  BE/src/loaders/mongoose.ts
  BE/src/models/account-book.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/accountbook/schema.ts
  BE/src/models/category/index.ts
  BE/src/models/category/schema.ts
  BE/src/models/defaultPaymentMethod.ts
  BE/src/models/paymentmethod/index.ts
  BE/src/models/paymentmethod/schema.ts
  BE/src/models/transaction/schema.ts
  BE/src/models/user.ts
  BE/src/models/user/index.ts
  BE/src/models/user/schema.ts
  BE/src/services/account-book.ts
  BE/src/services/auth.ts
  BE/src/services/defaultPaymentMethod.ts
  BE/tsconfig.json
  FE/src/components/PaymentMethod/Modal/modal.scss
  FE/src/components/transaction/list/transactions/transactions.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/pages/transaction/transaction.module.scss
Labels: backend

#68 Calendar detail info
  FE/src/components/Calendar/Calendar/calendar.scss
  FE/src/components/Calendar/Calendar/index.tsx
  FE/src/components/Calendar/DetailModal/detailModal.scss
  FE/src/components/Calendar/DetailModal/index.tsx
  FE/src/components/Calendar/TotalContent/index.tsx
  FE/src/components/Calendar/TotalContent/totalContent.scss
  FE/src/components/Calendar/index.tsx
  FE/src/components/CategoryChart/PieChart/index.tsx
  FE/src/components/CategoryChart/TableChart/index.tsx
  FE/src/components/Common/MenuBar/menubar.scss
  FE/src/components/PaymentMethod/AddTemplate/addForm.scss
  FE/src/components/PaymentMethod/AddTemplate/index.tsx
  FE/src/components/PaymentMethod/Modal/index.tsx
  FE/src/components/TransactionByDate/index.tsx
  FE/src/components/TransactionByDate/transactionByDate.scss
  FE/src/pages/Calendar/index.tsx
  FE/src/pages/Chart/index.tsx
  FE/src/service/useDefaultPayment.ts
  FE/src/store/DateInfo/dateInfoStore.ts
  FE/src/store/PaymentMethod/paymentMethodStore.ts
  FE/src/store/TransactionData/transactionData.ts
  FE/src/styles/values.scss
  FE/src/util/commaForMoney.ts
Labels: enhancement, frontend

#30 [BE] authorization 미들웨어 구현
  BE/src/controllers/auth.ts
  BE/src/loaders/error.ts
  BE/src/routes/api/index.ts
  BE/src/services/auth.ts
  BE/src/types/auth.ts
Labels: backend, enhancement

#66 [FE] 가계부 목록 페이지 목록과 생성 mobX로 상태관리
  FE/package-lock.json
  FE/package.json
  FE/src/api/accoun-book-list.ts
  FE/src/app.tsx
  FE/src/components/AccountBook/AccountBookControl/AccountBookControl.scss
  FE/src/components/AccountBook/AccountBookControl/index.tsx
  FE/src/components/AccountBook/AccountBookList/AccountBookList.scss
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/pages/AccountBook/AccountBookListPage.scss
  FE/src/pages/AccountBook/index.tsx
  FE/src/store/AccountBook/account-book.context.tsx
  FE/src/store/AccountBook/account-book.hook.ts
  FE/src/store/AccountBook/account-book.store.ts
Labels: enhancement, frontend

#70 [FE,BE] FE fetch 요청 헤더 추가 및 미들웨어 수정
  BE/src/controllers/auth.ts
  BE/src/services/auth/check.ts
  FE/src/service/fetch.ts
Labels: backend

#73 [BE] API 라우팅, 리팩토링
  BE/src/controllers/account-book.ts
  BE/src/controllers/auth.ts
  BE/src/controllers/category.ts
  BE/src/controllers/defaultPaymentMethod.ts
  BE/src/controllers/payment.ts
  BE/src/controllers/transaction.ts
  BE/src/controllers/user.ts
  BE/src/index.ts
  BE/src/interfaces/auth.ts
  BE/src/interfaces/error.ts
  BE/src/loaders/error.ts
  BE/src/loaders/koa.ts
  BE/src/models/transaction/index.ts
  BE/src/routes/api/account-book.ts
  BE/src/routes/api/account-book/category.ts
  BE/src/routes/api/account-book/index.ts
  BE/src/routes/api/account-book/payment.ts
  BE/src/routes/api/account-book/transaction.ts
  BE/src/routes/api/auth.ts
  BE/src/routes/api/defaultPaymentMethod.ts
  BE/src/routes/api/index.ts
  BE/src/routes/api/user.ts
  BE/src/routes/index.ts
  BE/src/services/auth/check.ts
  BE/src/services/auth/login.ts
  BE/src/services/auth/oauth.ts
  BE/src/services/transaction.ts
  BE/src/services/user.ts
  BE/tsconfig.json
Labels: backend

#76 Calendar refactoring
  FE/src/components/Calendar/Calendar/calendar.scss
  FE/src/components/Calendar/Calendar/index.tsx
  FE/src/components/Calendar/CalendarBody/calendarBody.scss
  FE/src/components/Calendar/CalendarBody/index.tsx
  FE/src/components/Calendar/DetailModal/detailModal.scss
  FE/src/components/Calendar/DetailModal/index.tsx
  FE/src/service/useDefaultPayment.ts
  FE/src/store/PaymentMethod/paymentMethodStore.ts
  FE/src/store/TransactionData/transactionData.ts
Labels: frontend, refactor

#74 [refactor] #37 가계부 목록 페이지 상태관리를 mobX에서 useState로 변경
  FE/src/api/accoun-book-list.ts
  FE/src/app.tsx
  FE/src/components/AccountBook/AccountBookAddForm/accountBookAddForm.scss
  FE/src/components/AccountBook/AccountBookAddForm/index.tsx
  FE/src/components/AccountBook/AccountBookControl/index.tsx
  FE/src/components/AccountBook/AccountBookList/AccountBookList.scss
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/pages/AccountBook/AccountBookListPage.scss
  FE/src/pages/AccountBook/index.tsx
  FE/src/store/AccountBook/account-book.hook.ts
Labels: frontend, refactor

#80 Accountbook select connect
  BE/src/controllers/account-book.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/transaction/schema.ts
  BE/src/services/account-book.ts
  FE/src/api/accoun-book-list.ts
  FE/src/app.tsx
  FE/src/components/AccountBook/AccountBookAddForm/accountBookAddForm.scss
  FE/src/components/AccountBook/AccountBookAddForm/index.tsx
  FE/src/components/AccountBook/AccountBookControl/AccountBookControl.scss
  FE/src/components/AccountBook/AccountBookControl/index.tsx
  FE/src/components/AccountBook/AccountBookList/AccountBookList.scss
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/components/Calendar/CalendarBody/index.tsx
  FE/src/components/Calendar/DetailModal/index.tsx
  FE/src/components/Calendar/TotalContent/index.tsx
  FE/src/components/Common/MenuBar/index.tsx
  FE/src/pages/AccountBook/AccountBookListPage.scss
  FE/src/pages/AccountBook/index.tsx
  FE/src/pages/Calendar/index.tsx
  FE/src/pages/Chart/index.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/service/useAccountBookSetting.ts
  FE/src/service/useDefaultPayment.ts
  FE/src/store/AccountBook/account-book.context.tsx
  FE/src/store/AccountBook/account-book.store.ts
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/store/AccountBook/accountBookDataContext.tsx
  FE/src/store/AccountBook/accountBookInfoHook.ts
  FE/src/store/TransactionData/transactionData.ts
  FE/src/store/TransactionData/transactionInfoHook.ts
Labels: backend, enhancement, frontend, refactor

#79 [BE] AccountBook API
  BE/src/controllers/account-book.ts
  BE/src/interfaces/accountbook.ts
  BE/src/interfaces/auth.ts
  BE/src/interfaces/category.ts
  BE/src/interfaces/payment-method.ts
  BE/src/interfaces/response.ts
  BE/src/interfaces/transaction.ts
  BE/src/loaders/error.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/accountbook/schema.ts
  BE/src/models/category/index.ts
  BE/src/models/category/schema.ts
  BE/src/models/paymentmethod/index.ts
  BE/src/models/paymentmethod/schema.ts
  BE/src/models/transaction/schema.ts
  BE/src/models/user/index.ts
  BE/src/models/user/schema.ts
  BE/src/services/account-book.ts
  BE/src/services/auth/check.ts
  BE/src/services/auth/login.ts
  BE/src/services/auth/oauth.ts
  BE/src/services/transaction.ts
  BE/src/utils/response.ts
  BE/tsconfig.json
Labels: backend

#83 Accountbook cud connect
  BE/src/controllers/account-book.ts
  BE/src/controllers/auth.ts
  BE/src/models/accountbook/index.ts
  BE/src/services/account-book.ts
  FE/src/api/accoun-book-list.ts
  FE/src/components/AccountBook/AccountBookAddForm/accountBookAddForm.scss
  FE/src/components/AccountBook/AccountBookAddForm/index.tsx
  FE/src/components/AccountBook/AccountBookControl/AccountBookControl.scss
  FE/src/components/AccountBook/AccountBookList/AccountBookList.scss
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/components/Calendar/CalendarBody/calendarBody.scss
  FE/src/components/Common/MenuBar/index.tsx
  FE/src/components/Common/MenuBar/menubar.scss
  FE/src/pages/AccountBook/AccountBookListPage.scss
  FE/src/pages/AccountBook/index.tsx
Labels: backend, enhancement, frontend, refactor

#86 UI refactor
  FE/src/app.scss
  FE/src/components/AccountBook/AccountBookControl/AccountBookControl.scss
  FE/src/components/Calendar/Calendar/calendar.scss
  FE/src/components/Calendar/Calendar/index.tsx
  FE/src/components/Calendar/CalendarBody/calendarBody.scss
  FE/src/components/Calendar/CalendarBody/index.tsx
  FE/src/components/Calendar/TotalContent/totalContent.scss
  FE/src/components/CategoryChart/PieChart/pieChart.scss
  FE/src/components/CategoryChart/TableChart/index.tsx
  FE/src/components/CategoryChart/TableChart/tableChart.scss
  FE/src/components/Chart/NavButton/navButton.scss
  FE/src/components/Common/MenuBar/menubar.scss
  FE/src/components/transaction/list/listcontainer.module.scss
  FE/src/styles/values.scss
Labels: frontend, refactor

#97 payement, accountbook Api connect
  FE/src/api/payment-method.ts
  FE/src/components/AccountBook/AccountBookList/AccountBookList.scss
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/components/Calendar/CalendarBody/calendarBody.scss
  FE/src/components/Calendar/DetailModal/detailModal.scss
  FE/src/components/PaymentMethod/AddTemplate/index.tsx
  FE/src/components/PaymentMethod/CardContainer/cardContainer.scss
  FE/src/components/PaymentMethod/CardContainer/index.tsx
  FE/src/components/PaymentMethod/Modal/index.tsx
  FE/src/components/PaymentMethod/Modal/modal.scss
  FE/src/service/fetch.ts
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/util/findSibling.ts
Labels: backend, enhancement, frontend

#102 [BE] csv import, export 위한 라우팅 분리
  BE/src/controllers/transaction.ts
  BE/src/routes/api/account-book/transaction.ts
Labels: backend

#100 [FE] Transaction add
  FE/.eslintrc.js
  FE/src/api/transaction.ts
  FE/src/app.tsx
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.scss
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/ContentInput/index.scss
  FE/src/components/transaction/TransactionAddModal/ContentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/DateInput/index.scss
  FE/src/components/transaction/TransactionAddModal/DateInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/MessageInput/index.scss
  FE/src/components/transaction/TransactionAddModal/MessageInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddForm/index.scss
  FE/src/components/transaction/TransactionAddModal/TransactionAddForm/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddModal.scss
  FE/src/components/transaction/TransactionAddModal/index.tsx
  FE/src/components/transaction/list/TransactionItem/TransactionItem.module.scss
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/TransactionsOfOneDay/index.tsx
  FE/src/components/transaction/list/listcontainer.module.scss
  FE/src/components/transaction/list/listcontainer.scss
  FE/src/components/transaction/list/listcontainer.tsx
  FE/src/components/transaction/list/transactions/index.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/store/TransactionFormModal/TransactionFormModalContext.tsx
  FE/src/store/TransactionFormModal/TransactionFormModalHook.ts
  FE/src/store/TransactionFormModal/TransactionFormModalStore.ts
  FE/src/util/calculateDate.ts
Labels: enhancement, frontend

#110 [FE,BE] Setting calendar startday
  BE/src/models/accountbook/index.ts
  FE/src/api/calendar-startday.ts
  FE/src/components/AccountBook/AccountBookControl/index.tsx
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/components/Calendar/Calendar/index.tsx
  FE/src/components/Calendar/CalendarBody/index.tsx
  FE/src/components/Calendar/CalendarHeader/index.tsx
  FE/src/components/Calendar/DetailModal/index.tsx
  FE/src/components/SettingBar/index.tsx
  FE/src/components/SettingContent/CalendarSetting/calendarSetting.scss
  FE/src/components/SettingContent/CalendarSetting/index.tsx
  FE/src/components/SettingContent/SaveModal/index.tsx
  FE/src/components/SettingContent/SaveModal/saveModal.scss
  FE/src/pages/SettingPage/index.tsx
  FE/src/pages/SettingPage/settingPage.scss
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/util/calendarTemplate.ts
Labels: backend, enhancement, frontend

#109 [FE] Transaction update
  BE/src/models/accountbook/index.ts
  FE/src/api/transaction.ts
  FE/src/app.tsx
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.scss
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/ContentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/MessageInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddForm/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddModal.scss
  FE/src/components/transaction/list/TransactionItem/TransactionItem.module.scss
  FE/src/components/transaction/list/TransactionItem/index.scss
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/TransactionsOfOneDay/TransactionsOfOneDay.module.scss
  FE/src/components/transaction/list/TransactionsOfOneDay/index.scss
  FE/src/components/transaction/list/TransactionsOfOneDay/index.tsx
  FE/src/components/transaction/list/filter/listfilter.modules.scss
  FE/src/components/transaction/list/filter/listfilter.tsx
  FE/src/components/transaction/list/listcontainer.scss
  FE/src/components/transaction/list/listcontainer.tsx
  FE/src/components/transaction/list/transactions/index.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/store/TransactionFormModal/TransactionFormModalStore.ts
Labels: enhancement, frontend

#112 [BE] 소셜관련기능 API 라우팅
  BE/src/controllers/social.ts
  BE/src/routes/api/account-book/index.ts
  BE/src/routes/api/account-book/social.ts
Labels: backend

#115 [FE] Setting category tab
  FE/src/api/category.ts
  FE/src/components/SettingContent/CalendarSetting/calendarSetting.scss
  FE/src/components/SettingContent/CategorySetting/CategoryModal/categoryModal.scss
  FE/src/components/SettingContent/CategorySetting/CategoryModal/index.tsx
  FE/src/components/SettingContent/CategorySetting/IncomeCategory/index.tsx
  FE/src/components/SettingContent/CategorySetting/SpendingCategory/index.tsx
  FE/src/components/SettingContent/CategorySetting/categorySetting.scss
  FE/src/components/SettingContent/CategorySetting/index.tsx
  FE/src/components/SettingContent/SaveModal/index.tsx
  FE/src/pages/SettingPage/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/styles/mixins.scss
Labels: enhancement, frontend

#119 [FE] Transaction delete
  FE/src/api/transaction.ts
  FE/src/components/Calendar/Calendar/index.tsx
  FE/src/components/Calendar/CalendarBody/index.tsx
  FE/src/components/SettingContent/CalendarSetting/calendarSetting.scss
  FE/src/components/SettingContent/CalendarSetting/index.tsx
  FE/src/components/SettingContent/SaveModal/index.tsx
  FE/src/components/transaction/TransactionAddModal/ContentInput/index.tsx
  FE/src/components/transaction/list/TransactionItem/index.scss
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/filter/listfilter.modules.scss
  FE/src/pages/SettingPage/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
Labels: enhancement, frontend

#124 [BE] 소셜관련 API 작업
  BE/.eslintrc.json
  BE/src/controllers/account-book.ts
  BE/src/controllers/social.ts
  BE/src/interfaces/accountbook.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/accountbook/schema.ts
  BE/src/routes/api/account-book/index.ts
  BE/src/routes/api/index.ts
  BE/src/routes/api/social.ts
  BE/src/services/account-book.ts
  BE/src/utils/random.ts
Labels: backend

#123 [FE] Transaction update 버튼 생성 및 수정, 삭제 버튼 나오는 방식 수정
  FE/src/components/transaction/list/TransactionItem/index.scss
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/listcontainer.scss
Labels: frontend

#127 Scss refactor layout
  FE/src/app.scss
  FE/src/components/AccountBook/AccountBookControl/AccountBookControl.scss
  FE/src/components/AccountBook/AccountBookList/AccountBookList.scss
  FE/src/components/Calendar/Calendar/calendar.scss
  FE/src/components/Calendar/CalendarBody/calendarBody.scss
  FE/src/components/Calendar/CalendarBody/index.tsx
  FE/src/components/Calendar/DetailModal/detailModal.scss
  FE/src/components/Calendar/TotalContent/totalContent.scss
  FE/src/components/CategoryChart/PieChart/pieChart.scss
  FE/src/components/CategoryChart/TableChart/tableChart.scss
  FE/src/components/Chart/NavButton/navButton.scss
  FE/src/components/Common/HeaderButton/headerButton.scss
  FE/src/components/Common/MenuBar/index.tsx
  FE/src/components/Common/MenuBar/menubar.scss
  FE/src/components/PaymentMethod/AddTemplate/addForm.scss
  FE/src/components/PaymentMethod/CardContainer/cardContainer.scss
  FE/src/components/PaymentMethod/Modal/modal.scss
  FE/src/components/PaymentMethod/NewMethod/newMethod.scss
  FE/src/components/SettingBar/settingBar.scss
  FE/src/components/SettingContent/CalendarSetting/calendarSetting.scss
  FE/src/components/SettingContent/CategorySetting/CategoryModal/categoryModal.scss
  FE/src/components/SettingContent/CategorySetting/categorySetting.scss
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.scss
  FE/src/components/transaction/TransactionAddModal/ContentInput/index.scss
  FE/src/components/transaction/TransactionAddModal/DateInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.scss
  FE/src/components/transaction/TransactionAddModal/TransactionAddModal.scss
  FE/src/components/transaction/list/TransactionItem/index.scss
  FE/src/components/transaction/list/TransactionsOfOneDay/index.scss
  FE/src/components/transaction/list/filter/listfilter.modules.scss
  FE/src/components/transaction/list/listcontainer.scss
  FE/src/components/transaction/list/transactions/transactions.module.scss
  FE/src/pages/AccountBook/AccountBookListPage.scss
  FE/src/pages/Chart/chart.scss
  FE/src/pages/Login/GithubLoginProcess/GithubLoginProcess.scss
  FE/src/pages/Login/NaverLoginProcess/NaverLoginProcess.scss
  FE/src/pages/Login/index.scss
  FE/src/pages/SettingPage/settingPage.scss
  FE/src/styles/mediaQuery.scss
  FE/src/styles/mixins.scss
  FE/src/styles/values.scss
Labels: enhancement, frontend

#129 [BE] github, naver 로그인시 프로필 이미지 받아오기
  BE/src/services/auth/oauth.ts
Labels: backend

#130 [FE] User social connect
  FE/src/api/invite-code.ts
  FE/src/api/social.ts
  FE/src/components/AccountBook/AccountBookAddForm/accountBookAddForm.scss
  FE/src/components/AccountBook/AccountBookAddForm/index.tsx
  FE/src/components/AccountBook/AccountBookControl/AccountBookControl.scss
  FE/src/components/AccountBook/AccountBookControl/index.tsx
  FE/src/components/SettingContent/CalendarSetting/WeekHeader/index.tsx
  FE/src/components/SettingContent/CalendarSetting/calendarSetting.scss
  FE/src/components/SettingContent/CategorySetting/CategoryModal/categoryModal.scss
  FE/src/components/SettingContent/CategorySetting/categorySetting.scss
  FE/src/components/SettingContent/UserSetting/InviteCode/index.tsx
  FE/src/components/SettingContent/UserSetting/InviteCode/inviteCode.scss
  FE/src/components/SettingContent/UserSetting/UserList/index.tsx
  FE/src/components/SettingContent/UserSetting/UserList/userList.scss
  FE/src/components/SettingContent/UserSetting/index.tsx
  FE/src/components/SettingContent/UserSetting/userSetting.scss
  FE/src/pages/AccountBook/index.tsx
  FE/src/pages/SettingPage/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/styles/mixins.scss
Labels: enhancement, frontend

#128 [FE] SMS 파싱을 통해서 데이터 추가
  FE/src/components/transaction/TransactionAddModal/MessageInputForm/index.tsx
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/index.tsx
  FE/src/components/transaction/list/TransactionItem/index.scss
  FE/src/service/smsParsing.ts
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/store/TransactionFormModal/TransactionFormModalStore.ts
Labels: enhancement, frontend

#126 [FE, BE] CSV로 거래내역 export, import
  BE/package-lock.json
  BE/package.json
  BE/src/controllers/transaction.ts
  BE/src/models/accountbook/index.ts
  BE/src/routes/api/account-book/transaction.ts
  BE/src/services/transaction.ts
  BE/src/utils/export.js
  BE/src/utils/transaction.csv
  BE/src/utils/transaction.json
  FE/package-lock.json
  FE/package.json
  FE/src/api/csv.ts
  FE/src/components/SettingContent/CSVSetting/csvSetting.scss
  FE/src/components/SettingContent/CSVSetting/index.tsx
  FE/src/service/export.ts
  FE/src/service/fetch.ts
Labels: backend, enhancement, frontend

#131 [BE] user 모델 수정
  BE/src/interfaces/auth.ts
  BE/src/models/user/index.ts
  BE/src/models/user/schema.ts
Labels: backend

#132 [BE] 코드생성시 가계부 정보 보내주기
  BE/src/controllers/account-book.ts
  BE/src/models/accountbook/index.ts
  BE/src/services/account-book.ts
Labels: backend

#135 [fix] 배포판 핫픽스
  BE/src/interfaces/auth.ts
  BE/src/models/user/schema.ts
Labels: release

#140 Api validation refactor
  BE/src/controllers/defaultPaymentMethod.ts
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/components/PaymentMethod/AddTemplate/index.tsx
  FE/src/components/PaymentMethod/CardContainer/index.tsx
  FE/src/components/SettingContent/CSVSetting/CSVExport/index.tsx
  FE/src/components/SettingContent/CSVSetting/CSVImport/index.tsx
  FE/src/components/SettingContent/CSVSetting/index.tsx
  FE/src/components/SettingContent/CategorySetting/CategoryModal/index.tsx
  FE/src/components/SettingContent/SaveModal/index.tsx
  FE/src/components/SettingContent/UserSetting/InviteCode/index.tsx
  FE/src/components/SettingContent/UserSetting/UserList/index.tsx
  FE/src/pages/AccountBook/index.tsx
  FE/src/pages/DefaultTemplate/index.tsx
  FE/src/pages/DefaultTemplate/paymentPage.module.scss
  FE/src/store/PaymentMethod/paymentMethodStore.ts
  FE/src/util/message.ts
Labels: backend, frontend, refactor

#138 [feat] #113 BE token -> accesstoken, refreshtoken
  BE/package-lock.json
  BE/package.json
  BE/src/controllers/auth.ts
  BE/src/interfaces/auth.ts
  BE/src/models/user/index.ts
  BE/src/routes/api/auth.ts
  BE/src/services/auth/check.ts
  BE/src/services/auth/login.ts
  BE/src/services/auth/oauth.ts
  BE/src/utils/response.ts
  FE/src/api/auth.ts
  FE/src/api/refresh.ts
  FE/src/service/fetch.ts
  FE/src/service/useLoginCheck.ts
Labels: backend

#143 [refactor] Function bug refactor
  FE/src/components/AccountBook/AccountBookAddForm/index.tsx
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/components/Calendar/TotalContent/index.tsx
  FE/src/components/Chart/FilteringButton/filtering-button.scss
  FE/src/components/Chart/FilteringButton/index.tsx
  FE/src/components/Common/SaveModal/index.tsx
  FE/src/components/Common/SaveModal/saveModal.scss
  FE/src/components/PaymentMethod/CardContainer/index.tsx
  FE/src/components/PaymentMethod/Modal/index.tsx
  FE/src/components/SettingContent/CSVSetting/CSVImport/index.tsx
  FE/src/components/SettingContent/CalendarSetting/calendarSetting.scss
  FE/src/components/SettingContent/CalendarSetting/index.tsx
  FE/src/components/SettingContent/CategorySetting/CategoryModal/categoryModal.scss
  FE/src/components/SettingContent/CategorySetting/CategoryModal/index.tsx
  FE/src/components/SettingContent/UserSetting/UserList/index.tsx
  FE/src/components/SettingContent/UserSetting/UserList/userList.scss
  FE/src/components/SettingContent/UserSetting/index.tsx
  FE/src/pages/AccountBook/index.tsx
  FE/src/pages/Chart/chart.scss
  FE/src/pages/Chart/index.tsx
  FE/src/pages/Login/GithubLoginProcess/GithubLoginProcess.scss
  FE/src/pages/Login/NaverLoginProcess/NaverLoginProcess.scss
  FE/src/pages/Login/index.tsx
  FE/src/pages/SettingPage/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/styles/mixins.scss
  FE/src/util/chartColorCollection.ts
Labels: enhancement, frontend

#145 [FE] 거래내역 drag and drop 및 거래내역 추가 모달 수정
  FE/package-lock.json
  FE/package.json
  FE/src/app.scss
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.scss
  FE/src/components/transaction/TransactionAddModal/DateInput/index.scss
  FE/src/components/transaction/TransactionAddModal/DateInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.tsx
  FE/src/components/transaction/list/TransactionItem/index.scss
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/TransactionsOfOneDay/index.scss
  FE/src/components/transaction/list/TransactionsOfOneDay/index.tsx
  FE/src/components/transaction/list/transactions/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/styles/values.scss
  FE/src/util/calculate-cursor.ts
Labels: frontend

#149 [BE] csv export, import Refactor & ErrorHandling
  BE/src/services/transaction.ts
  FE/src/api/csv.ts
  FE/src/components/SettingContent/CSVSetting/CSVImport/index.tsx
  FE/src/service/export.ts
Labels: backend, refactor

#150 [BE] 연월별로 거래내역 읽어오는 API
  BE/src/controllers/account-book.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/transaction/schema.ts
  BE/src/routes/api/account-book/index.ts
  BE/src/routes/api/account-book/transaction.ts
  BE/src/services/account-book.ts
  BE/src/services/transaction.ts
  FE/src/components/AccountBook/AccountBookAddForm/JoinForm/index.tsx
Labels: backend

#152 [FE] Accountbook api modify
  FE/.env.production
  FE/src/api/accoun-book-list.ts
  FE/src/service/useAccountBookSetting.ts
  FE/src/store/AccountBook/accountBookData.ts
Labels: frontend

#153 [FE, BE] template.csv 다운로드 구현
  BE/src/controllers/transaction.ts
  BE/src/routes/api/account-book/transaction.ts
  BE/src/services/transaction.ts
  FE/public/template.csv
  FE/src/api/csv.ts
  FE/src/components/SettingContent/CSVSetting/CSVExport/csvExport.scss
  FE/src/components/SettingContent/CSVSetting/CSVExport/index.tsx
  FE/src/service/export.ts
  FE/src/styles/mixins.scss
  FE/webpack.config.js
Labels: backend, enhancement, frontend

#156 [fix] 코드 프리징 전 1차 Bug fix
  BE/src/models/accountbook/index.ts
  BE/src/models/transaction/schema.ts
  BE/src/services/auth/check.ts
  FE/src/api/accoun-book-list.ts
  FE/src/components/CategoryChart/TableChart/tableChart.scss
  FE/src/components/SettingContent/CSVSetting/CSVImport/index.tsx
  FE/src/components/SettingContent/CSVSetting/index.tsx
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/filter/listfilter.scss
  FE/src/components/transaction/list/filter/listfilter.tsx
  FE/src/components/transaction/list/listcontainer.scss
  FE/src/pages/Chart/index.tsx
  FE/src/pages/SettingPage/index.tsx
Labels: backend, bug, frontend

#154 [FE] 거래내역 페이지 및 거래내역 form 타입 추가
  FE/.babelrc
  FE/.eslintrc.js
  FE/package-lock.json
  FE/package.json
  FE/src/api/accoun-book-list.ts
  FE/src/api/auth.ts
  FE/src/api/transaction.ts
  FE/src/components/Login/GithubLoginButton.tsx
  FE/src/components/Login/NaverLoginButton.tsx
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/ContentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/DateInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/MessageInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/MessageInputForm/index.tsx
  FE/src/components/transaction/TransactionAddModal/PaymentInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddForm/index.tsx
  FE/src/components/transaction/TransactionAddModal/index.tsx
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/TransactionsOfOneDay/index.tsx
  FE/src/components/transaction/list/filter/listfilter.tsx
  FE/src/components/transaction/list/listcontainer.tsx
  FE/src/components/transaction/list/transactions/index.tsx
  FE/src/interfaces/accountbook.ts
  FE/src/interfaces/category.ts
  FE/src/interfaces/fetch.ts
  FE/src/interfaces/payment.ts
  FE/src/interfaces/transaction-components.ts
  FE/src/interfaces/transaction-form-modal-store.ts
  FE/src/interfaces/transaction.ts
  FE/src/interfaces/user.ts
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/store/TransactionFormModal/TransactionFormModalHook.ts
  FE/src/store/TransactionFormModal/TransactionFormModalStore.ts
  FE/src/types/transaction.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: frontend, refactor

#158 [FE] Transaction form validation
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddForm/index.tsx
  FE/src/service/transaction-form-validation.ts
Labels: frontend

#159 [FE] Filter 초기화 버튼 생성
  FE/src/components/transaction/list/filter/listfilter.scss
  FE/src/components/transaction/list/filter/listfilter.tsx
  FE/src/styles/values.scss
Labels: frontend

#160 [FE] drag and drop으로 바꿨을 때 마지막 위치로 이동하도록 수정
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/TransactionsOfOneDay/index.tsx
  FE/src/store/AccountBook/accountBookData.ts
Labels: frontend

#162 [fix] Transaction Fetch
  BE/.eslintrc.json
  BE/.prettierrc.json
  BE/package-lock.json
  BE/package.json
  BE/src/config/index.ts
  BE/src/controllers/account-book.ts
  BE/src/controllers/auth.ts
  BE/src/controllers/category.ts
  BE/src/controllers/defaultPaymentMethod.ts
  BE/src/controllers/payment.ts
  BE/src/controllers/social.ts
  BE/src/controllers/transaction.ts
  BE/src/controllers/user.ts
  BE/src/index.ts
  BE/src/interfaces/accountbook.ts
  BE/src/interfaces/auth.ts
  BE/src/interfaces/response.ts
  BE/src/interfaces/transaction.ts
  BE/src/loaders/error.ts
  BE/src/loaders/index.ts
  BE/src/loaders/koa.ts
  BE/src/loaders/mongoose.ts
  BE/src/loaders/redis.ts
  BE/src/middlewares/check-token.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/accountbook/schema.ts
  BE/src/models/category/schema.ts
  BE/src/models/paymentmethod/schema.ts
  BE/src/models/transaction/index.ts
  BE/src/models/transaction/schema.ts
  BE/src/models/user/index.ts
  BE/src/routes/api/account-book/category.ts
  BE/src/routes/api/account-book/index.ts
  BE/src/routes/api/account-book/payment.ts
  BE/src/routes/api/account-book/transaction.ts
  BE/src/routes/api/auth.ts
  BE/src/routes/api/defaultPaymentMethod.ts
  BE/src/routes/api/index.ts
  BE/src/routes/api/social.ts
  BE/src/routes/index.ts
  BE/src/services/account-book.ts
  BE/src/services/auth/check.ts
  BE/src/services/auth/login.ts
  BE/src/services/auth/oauth.ts
  BE/src/services/category.ts
  BE/src/services/defaultPaymentMethod.ts
  BE/src/services/payment-method.ts
  BE/src/services/redis.ts
  BE/src/services/transaction.ts
  BE/src/services/user.ts
  BE/src/utils/random.ts
  BE/src/utils/response.ts
  BE/tsconfig-paths-bootstrap.js
  BE/tsconfig.json
  FE/src/api/accoun-book-list.ts
  FE/src/components/SettingContent/UserSetting/InviteCode/index.tsx
Labels: backend, bug, frontend

#167 Export import refactor
  BE/src/controllers/account-book.ts
  BE/src/controllers/category.ts
  BE/src/controllers/transaction.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/transaction/index.ts
  BE/src/services/auth/login.ts
  BE/src/services/transaction.ts
  BE/src/utils/export.js
  FE/src/api/refresh.ts
  FE/src/service/fetch.ts
Labels: backend, refactor

#168 [FE] 거래내역 안의 스크롤을 밖으로 분리
  FE/src/components/Common/MenuBar/menubar.scss
  FE/src/components/transaction/list/filter/listfilter.scss
  FE/src/components/transaction/list/listcontainer.scss
  FE/src/pages/transaction/transaction.scss
Labels: frontend

#169 [fix] react array key값 부여 및 캘리더페이지 스크롤 문제 해결
  BE/src/models/transaction/index.ts
  BE/src/services/transaction.ts
  FE/src/api/auth.ts
  FE/src/components/AccountBook/AccountBookAddForm/JoinForm/index.tsx
  FE/src/components/AccountBook/AccountBookList/index.tsx
  FE/src/components/Calendar/Calendar/calendar.scss
  FE/src/components/Calendar/CalendarBody/calendarBody.scss
  FE/src/components/Calendar/CalendarBody/index.tsx
  FE/src/components/PaymentMethod/CardContainer/cardContainer.scss
  FE/src/components/PaymentMethod/NewMethod/index.tsx
  FE/src/components/SettingContent/CategorySetting/IncomeCategory/index.tsx
  FE/src/components/SettingContent/CategorySetting/SpendingCategory/index.tsx
  FE/src/components/SettingContent/UserSetting/InviteCode/index.tsx
  FE/src/components/SettingContent/UserSetting/UserList/index.tsx
  FE/src/components/transaction/TransactionAddModal/CategoryInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddForm/index.tsx
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/pages/Calendar/index.tsx
  FE/src/pages/Chart/index.tsx
  FE/src/pages/Login/NaverLoginProcess/index.tsx
  FE/src/pages/SettingPage/index.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/service/transaction-form-validation.ts
  FE/src/service/useLoginCheck.ts
  FE/src/store/AccountBook/accountBookData.ts
  FE/src/store/Theme/themeStore.ts
Labels: bug, frontend

#173 Develop
  BE/src/controllers/account-book.ts
  BE/src/controllers/category.ts
  BE/src/controllers/transaction.ts
  BE/src/loaders/mongoose.ts
  BE/src/loaders/redis.ts
  BE/src/models/accountbook/index.ts
  BE/src/models/transaction/index.ts
  BE/src/services/auth/login.ts
  BE/src/services/transaction.ts
  BE/src/utils/export.js
  FE/public/index.html
  FE/src/api/refresh.ts
  FE/src/components/AccountBook/AccountBookAddForm/JoinForm/index.tsx
  FE/src/components/AccountBook/AccountBookAddForm/index.tsx
  FE/src/components/Calendar/DetailModal/detailModal.scss
  FE/src/components/Calendar/DetailModal/index.tsx
  FE/src/components/Common/MenuBar/menubar.scss
  FE/src/components/Common/SaveModal/index.tsx
  FE/src/components/Common/SaveModal/saveModal.scss
  FE/src/components/Login/LoginButton.scss
  FE/src/components/PaymentMethod/Modal/modal.scss
  FE/src/components/SettingContent/CategorySetting/CategoryModal/categoryModal.scss
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.scss
  FE/src/components/transaction/TransactionAddModal/PriceInput/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddForm/index.tsx
  FE/src/components/transaction/TransactionAddModal/TransactionAddModal.scss
  FE/src/components/transaction/TransactionAddModal/index.tsx
  FE/src/components/transaction/list/TransactionItem/index.scss
  FE/src/components/transaction/list/TransactionItem/index.tsx
  FE/src/components/transaction/list/filter/listfilter.scss
  FE/src/components/transaction/list/filter/listfilter.tsx
  FE/src/components/transaction/list/listcontainer.scss
  FE/src/pages/AccountBook/index.tsx
  FE/src/pages/Calendar/index.tsx
  FE/src/pages/Chart/index.tsx
  FE/src/pages/SettingPage/index.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/pages/transaction/transaction.scss
  FE/src/service/fetch.ts
  FE/src/service/smsParsing.ts
  FE/src/service/useAccountBookSetting.ts
  FE/src/service/useLoginCheck.ts
  FE/src/styles/mixins.scss
  FE/src/styles/values.scss
Labels: bug, frontend, refactor
