Repository boostcamp-2020/Project16-C-Account-Book, pull requests merged in 2020-11, with the labels that each got.

#9 [FE, BE] 개발 환경 설정
  BE/.eslintrc.json
  BE/.gitignore
  BE/.prettierrc.json
  BE/package-lock.json
  BE/package.json
  BE/src/api/transaction.ts
  BE/src/api/user.ts
  BE/src/index.ts
  BE/src/loaders/koa-loader.ts
  BE/src/routes/index.ts
  BE/src/types/error.ts
  BE/tsconfig.json
  FE/.babelrc
  FE/.eslintrc.js
  FE/.gitignore
  FE/.prettierrc.js
  FE/jest.config.js
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/app.tsx
  FE/src/index.tsx
  FE/tsconfig.json
  FE/webpack.config.js
Labels: backend, documentation, frontend

#13 [BE] merge code
  BE/src/api/transaction.ts
  BE/src/api/user.ts
  BE/src/index.ts
  BE/src/loaders/error.ts
  BE/src/loaders/koa-loader.ts
  BE/src/loaders/koa.ts
Labels: backend

#15 [BE] npm run dev 문제 해결, user Router 설계로 BE 설계 가닥잡기
  .github/PULL_REQUEST_TEMPLATE.md
  BE/nodemon.json
  BE/package.json
  BE/src/controllers/user.ts
  BE/src/routes/api/user.ts
  BE/src/services/user.ts
  BE/tsconfig-paths-bootstrap.js
  BE/tsconfig.json
  README.md
Labels: backend

#12 [FE] Payment method page
  BE/tsconfig.json
  FE/.eslintrc.js
  FE/package-lock.json
  FE/package.json
  FE/src/app.scss
  FE/src/app.tsx
  FE/src/components/Common/MenuBar/index.tsx
  FE/src/components/Common/MenuBar/menubar.module.scss
  FE/src/components/PaymentMethod/AddTemplate/addForm.module.scss
  FE/src/components/PaymentMethod/AddTemplate/index.tsx
  FE/src/components/PaymentMethod/CardContainer/cardContainer.module.scss
  FE/src/components/PaymentMethod/CardContainer/index.tsx
  FE/src/components/PaymentMethod/Modal/index.tsx
  FE/src/components/PaymentMethod/Modal/modal.scss
  FE/src/components/PaymentMethod/NewMethod/index.tsx
  FE/src/components/PaymentMethod/NewMethod/newMethod.scss
  FE/src/pages/PaymentMethod/index.tsx
  FE/src/pages/PaymentMethod/paymentPage.module.scss
  FE/src/store/PaymentMethod/paymentMethodContext.tsx
  FE/src/store/PaymentMethod/paymentMethodHook.ts
  FE/src/store/PaymentMethod/paymentMethodStore.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: enhancement, frontend

#18 Default payment method api
  .github/reviewer-lottery.yml
  .github/workflows/reviewer_lottery.yml
  BE/src/controllers/defaultPaymentMethod.ts
  BE/src/controllers/user.ts
  BE/src/models/defaultPaymentMethod.ts
  BE/src/routes/api/defaultPaymentMethod.ts
  BE/src/routes/api/index.ts
  BE/src/services/defaultPaymentMethod.ts
  BE/src/services/user.ts
Labels: backend, enhancement

#17 [FE] Loginpage 버튼 생성
  BE/src/index.ts
  BE/src/routes/index.ts
  BE/tsconfig.json
  FE/.eslintrc.js
  FE/package-lock.json
  FE/package.json
  FE/public/images/github-logo.svg
  FE/src/app.tsx
  FE/src/components/Login/GithubLoginButton.scss
  FE/src/components/Login/GithubLoginButton.tsx
  FE/src/components/Login/index.scss
  FE/src/components/Login/index.tsx
  FE/src/index.scss
  FE/src/index.tsx
  FE/webpack.config.js
Labels: frontend

#21 [feat] #10 Database로부터 Default 결제수단을 받아와서 사용 할 수 있도록 연결
  FE/src/api/defaultPaymentMethod.ts
  FE/src/pages/PaymentMethod/index.tsx
  FE/src/service/fetch.ts
Labels: backend, enhancement, frontend

#24 [merge] develop <- acbook-list-api
  BE/src/controllers/account-book.ts
  BE/src/models/account-book.ts
  BE/src/routes/api/account-book.ts
  BE/src/routes/api/index.ts
  BE/src/services/account-book.ts
Labels: backend, enhancement

#28 [FE] 가계부 내역 레이아웃
  FE/src/transaction/components/date/date.module.scss
  FE/src/transaction/components/date/date.tsx
  FE/src/transaction/components/date/month/month.module.scss
  FE/src/transaction/components/date/month/month.tsx
  FE/src/transaction/components/date/year/year.module.scss
  FE/src/transaction/components/date/year/year.tsx
  FE/src/transaction/components/list/filter/listfilter.modules.scss
  FE/src/transaction/components/list/filter/listfilter.tsx
  FE/src/transaction/components/list/listcontainer.module.scss
  FE/src/transaction/components/list/listcontainer.tsx
  FE/src/transaction/components/list/transactions/transactions.module.scss
  FE/src/transaction/components/list/transactions/transactions.tsx
  FE/src/transaction/components/menubar/menubar.module.scss
  FE/src/transaction/components/menubar/menubar.tsx
  FE/src/transaction/transaction.module.scss
  FE/src/transaction/transaction.tsx
Labels: frontend

#26 Create common component & Create Calendar
  FE/package.json
  FE/public/index.html
  FE/src/app.tsx
  FE/src/components/Calendar/calendar.scss
  FE/src/components/Calendar/index.tsx
  FE/src/components/Common/MenuBar/index.tsx
  FE/src/components/Common/MenuBar/menubar.module.scss
  FE/src/components/PaymentMethod/NewMethod/index.tsx
  FE/src/pages/Calendar/calendar.module.scss
  FE/src/pages/Calendar/index.tsx
  FE/src/pages/defaultTemplate/index.tsx
  FE/src/pages/defaultTemplate/paymentPage.module.scss
  FE/src/service/fetch.ts
  FE/src/store/DateInfo/dateInfoContext.tsx
  FE/src/store/DateInfo/dateInfoHook.ts
  FE/src/store/DateInfo/dateInfoStore.ts
  FE/src/store/PaymentMethod/paymentMethodStore.ts
  FE/src/util/calculateDate.ts
Labels: enhancement, frontend

#25 [FE] Github 로그인
  BE/.env.template
  BE/package-lock.json
  BE/package.json
  BE/src/controllers/auth.ts
  BE/src/loaders/mongoose.ts
  BE/src/models/user.ts
  BE/src/routes/api/auth.ts
  BE/src/routes/api/index.ts
  BE/src/services/auth.ts
  BE/src/services/user.ts
  FE/.env.template
  FE/src/api/auth.ts
  FE/src/components/Login/GithubLoginButton.tsx
  FE/src/components/Login/GithubLoginProcess.scss
  FE/src/components/Login/GithubLoginProcess.tsx
  FE/src/index.scss
Labels: backend, frontend

#32 Payment method modal fix
  FE/src/api/defaultPaymentMethod.ts
  FE/src/components/Calendar/calendar.scss
  FE/src/components/Common/MenuBar/menubar.module.scss
  FE/src/components/PaymentMethod/CardContainer/cardContainer.module.scss
  FE/src/pages/Calendar/index.tsx
  FE/src/pages/defaultTemplate/index.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/service/useDefaultPayment.ts
  FE/src/store/PaymentMethod/paymentMethodStore.ts
Labels: bug, frontend

#35 Islogin routing
  FE/package-lock.json
  FE/package.json
  FE/src/pages/Calendar/index.tsx
  FE/src/pages/transaction/index.tsx
  FE/src/service/useLoginCheck.ts
  FE/src/store/DateInfo/dateInfoContext.tsx
  FE/src/store/DateInfo/dateInfoHook.ts
  FE/src/store/PaymentMethod/paymentMethodContext.tsx
  FE/src/store/PaymentMethod/paymentMethodHook.ts
Labels: enhancement, frontend

#62 Pie chart svg
  FE/package-lock.json
  FE/package.json
  FE/src/app.tsx
  FE/src/components/Calendar/calendar.scss
  FE/src/components/CategoryChart/PieChart/index.tsx
  FE/src/components/CategoryChart/PieChart/pieChart.scss
  FE/src/components/CategoryChart/TableChart/index.tsx
  FE/src/components/CategoryChart/TableChart/tableChart.scss
  FE/src/components/Chart/NavButton/index.tsx
  FE/src/components/Chart/NavButton/navButton.scss
  FE/src/components/Common/MenuBar/index.tsx
  FE/src/components/Common/MenuBar/menubar.module.scss
  FE/src/components/DateChart/LineChart/index.tsx
  FE/src/components/DateChart/LineChart/lineChart.scss
  FE/src/components/PaymentMethod/NewMethod/index.tsx
  FE/src/components/transaction/list/listcontainer.module.scss
  FE/src/pages/Calendar/calendar.module.scss
  FE/src/pages/Chart/chart.scss
  FE/src/pages/Chart/index.tsx
  FE/src/store/DateInfo/dateInfoContext.tsx
  FE/src/store/PaymentMethod/paymentMethodContext.tsx
  FE/src/store/TransactionData/transactionData.ts
  FE/src/store/TransactionData/transactionDataContext.tsx
  FE/src/store/TransactionData/transactionInfoHook.ts
  FE/src/util/chartColorCollection.ts
Labels: enhancement, frontend
